# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit yieldcurves.Rmd to modify this file

## ----setup, include = FALSE---------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = "center", out.width = "100%")


## ----ns-svensson, fig.cap = "Nelson-Siegel and Svensson fits to the US Treasury yield curve, most recent trading day. Points are the Constant Maturity Treasury rates from FRED at ten maturities. Solid line: Nelson-Siegel, RMSE 4.5 basis points. Dashed: Svensson, RMSE 2.9 basis points. Maturity on a log scale.", fig.alt = "A scatter plot of US Treasury yields against maturity on a log scale from three months to thirty years. Ten points trace an upward-sloping curve. Two fitted lines overlay the points: a solid Nelson-Siegel line and a dashed Svensson line. The two lines are very close at short and medium maturities and diverge slightly at the long end."----
knitr::include_graphics("figures/fig1_ns_svensson.pdf")


## ----params-------------------------------------------------------------------
params <- data.frame(
  Parameter = c("$\\beta_0$", "$\\beta_1$", "$\\beta_2$", "$\\beta_3$",
                "$\\tau_1$", "$\\tau_2$", "RMSE (bps)"),
  `Nelson-Siegel` = c("0.0536", "-0.0162", "-0.0210", "---", "---", "---", "4.5"),
  `Svensson` = c("0.0455", "-0.0082", "0.0578", "-0.0459", "8.0000", "5.0000", "2.9"),
  check.names = FALSE, stringsAsFactors = FALSE
)
knitr::kable(params, caption = "Parameter estimates for Nelson-Siegel and Svensson fits on the most recent US Treasury curve. Rates are in decimal units. The Nelson-Siegel level $\\beta_0$ is the asymptotic long-run rate. The negative slope $\\beta_1$ reflects the upward-sloping curve at the observation date. RMSE in basis points.", booktabs = TRUE, align = "lrr", escape = FALSE)


## ----forward, fig.cap = "Spot and instantaneous forward rates from a Nelson-Siegel fit to the most recent US Treasury curve. Spot (zero) rate in blue, instantaneous forward in red dashed. The forward curve lies above the spot curve wherever the spot curve is upward-sloping, with the gap widening at maturities where the spot rate rises most steeply.", fig.alt = "A line chart of US Treasury yields against maturity from zero to thirty years. A solid blue line is the spot rate curve, rising from about four per cent at the short end to about five per cent at the long end. A red dashed line is the instantaneous forward rate curve, which sits above the spot curve where the spot curve rises and converges to it at the long end."----
knitr::include_graphics("figures/fig2_forward.pdf")


## ----duration, fig.cap = "Modified duration versus maturity for zero-coupon and 5 per cent semi-annual coupon bonds. Zero-coupon duration (solid blue) equals maturity minus a small yield-dependent adjustment. A 5 per cent semi-annual coupon bond (red dashed) has substantially lower duration than a zero-coupon bond of the same maturity because the coupon cash flows carry weight at intermediate dates. Yields at each maturity read from a Nelson-Siegel fit to the current US Treasury curve.", fig.alt = "A line chart of modified duration against maturity from zero to thirty years. A solid blue line for zero-coupon bonds rises roughly linearly from zero to about twenty-eight years. A red dashed line for a 5 per cent semi-annual coupon bond sits below the zero-coupon line throughout, rising from zero to about fifteen years, with the gap widening at longer maturities."----
knitr::include_graphics("figures/fig4_duration.pdf")


## ----pca, fig.cap = "First three principal-component loadings of monthly US Treasury curve changes, 2019 to current. PC1 (level, blue) is roughly flat across maturities, indicating a parallel shift. PC2 (slope, red) is monotonically increasing with maturity, flipping sign around the 3- to 5-year maturity. PC3 (curvature, green) is humped with peaks at the short and long ends and a trough in the intermediate maturities. The three components together explain 99.9 per cent of variation.", fig.alt = "A line chart of principal component loadings against maturity from zero to thirty years. The first principal component (blue) is roughly flat around 0.4 across maturities, the classical level factor. The second principal component (red) starts negative at short maturities, crosses zero near five years, and rises to positive values at long maturities, the slope factor. The third principal component (green) is humped, positive at short and long ends and negative in the middle, the curvature factor."----
knitr::include_graphics("figures/fig3_pca.pdf")


## ----carry, fig.cap = "Expected three-month return decomposed into carry and roll-down, US Treasury curve at the most recent date. Bars are in basis points. Carry (blue) is the bond yield less the short-end funding rate (here the 3-month Treasury yield), scaled to the three-month horizon. Roll-down (red) is the capital gain from being revalued at the shorter-maturity yield implied by the current curve, assuming the curve does not shift. The 30-year point has the largest carry because the curve is upward-sloping, but modest roll-down because the curve is nearly flat at the long end.", fig.alt = "A grouped bar chart of expected three-month return contributions in basis points against maturity from two to thirty years. For each maturity there are two bars: blue for carry and red for roll-down. Carry rises with maturity; roll-down is largest at the belly of the curve (five to ten years) and smaller at both the short and long ends."----
knitr::include_graphics("figures/fig5_carry.pdf")


## ----curves, fig.cap = "US Treasury yield curves at three dates: pre-pandemic, rate peak, and most recent. Points are FRED Constant Maturity Treasury rates at ten maturities. Lines are Nelson-Siegel fits. December 2019 shows a flat low-rate curve. October 2023 shows an inverted curve around the 2- to 5-year belly. The most recent curve has re-steepened as front-end rates have fallen from their peak.", fig.alt = "A line chart of US Treasury yields against maturity on a log scale from three months to thirty years. Three curves are shown: a low and flat curve for December 2019 near two per cent, an inverted curve for October 2023 with short rates above long rates around five per cent, and a more recent upward-sloping curve between four and five per cent."----
knitr::include_graphics("figures/fig6_curves.pdf")

